language: python

python: 2.7

sudo: required

env:
  global:
   - PYENV_ROOT="$HOME/.pyenv"
   - PYENV_PACKAGE="https://github.com/yyuu/pyenv/archive/v1.0.7.tar.gz"
   - PYENV_VERSION="3.6.0"

matrix:
  include:
    #- os: osx
    #  language: generic
    #  env: TOX_ENV=py27
    - os: osx
      language: generic
      env: TOX_ENV=py36
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

services:
  - mongodb
  - redis-server

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install mongodb
      sudo mkdir -p /data/db
      brew services start mongodb
      brew install redis
      brew services start redis
      brew install mysql
      brew services start mysql
      brew unlink postgres
      brew install postgres
      export PG_DATA=$(brew --prefix)/var/postgres
      rm -rf $PG_DATA
      initdb $PG_DATA -E utf8
      pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
      createuser -s postgres
    fi
  - cat /etc/hosts
  - cat /etc/resolv.conf
  - hostname
  - ulimit -n 2048
  - ulimit -a

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  #- |
  #  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #    brew update
  #    brew unlink python
  #    brew unlink python3
  #    if [[ TOX_ENV == py2* ]]; then
  #      brew install python
  #    else
  #      brew install python3
  #    fi
  #  fi
  #- |
  #  if [[ TOX_ENV == py2* ]]; then
  #    pip install -U pip setuptools tox
  #  else
  #    pip3 install -U pip setuptools tox
  #  fi
  - brew upgrade pyenv

before_script:
  - mysql -u root -e 'create database grab_test'
  - psql -U postgres -c 'create database grab_test'
  # Override test settings with travis settings 
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cp travis_linux_settings.py test_settings_local.py
    else
      cp travis_osx_settings.py test_settings_local.py
    fi

script:

  - if [[ ! -z "$VIRTUAL_ENV" ]]; then deactivate; fi
  #- curl -fsSL $PYENV_PACKAGE | tar -xz -C "$PYENV_ROOT" --strip-components 1
  #- export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install "$PYENV_VERSION"
  - pyenv global "$PYENV_VERSION"
  - python -m pip install -U pip setuptools tox
  # Run tests and find out the test coverage
  - tox -e $TOX_ENV

after_success:
  - coveralls
