language: python

python: 2.7

sudo: required

matrix:
  include:
    - os: osx
      language: generic
      env: TOX_ENV=py27-nobackend
    - os: osx
      language: generic
      env: TOX_ENV=py34-nobackend
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

services:
  - mongodb
  - redis-server

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install mongodb
      sudo mkdir -p /data/db
      brew services start mongodb
      brew install redis
      brew services start redis
    fi

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew unlink python
      brew unlink python3
      if [[ TOX_ENV == py2* ]]; then
        brew install python
      else
        brew install python3
      fi
    fi
  - |
    if [[ TOX_ENV == py2* ]]; then
      pip install -U pip setuptools tox
    else
      pip3 install -U pip setuptools tox
    fi

before_script:
  - mysql -e 'create database grab_test'
  - psql -c 'create database grab_test' -U postgres

script:
    # Override test settings with travis settings 
    - cp travis_settings.py test_settings_local.py
    # Run tests and find out the test coverage
    - tox -e $TOX_ENV

#after_success:
#  - coveralls
