language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install --use-mirrors tornado
  - pip install -r requirements.txt --use-mirrors
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - python setup.py develop

script:
  - coverage run --source=grab runtest.py --test-all --extra
