language: python

python: 2.7

# sudo: required

matrix:
  include:
    - os: osx
      language: generic
      env: TOX_ENV=py27-nobackend
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - |
    if [[ $TRAVIS_OS_NAME ]]; then
      brew update
      brew install python
    fi
  - pip install -U pip setuptoos tox

script:
    - tox -e $TOX_ENV

#after_success:
#  - coveralls
