language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements_travis.txt
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - python setup.py develop

script:
    # Override test settings with travis settings 
    - cp travis_settings.py test_settings_local.py
    # Run tests and find out the test coverage
    - coverage run --source=grab runtest.py --test-all --extra --backend-mongo --backend-mysql

after_success:
  - coveralls

services:
  - mongodb

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false
