environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
  - "%PYTHON%/python.exe -m pip install tox"

build: off

before_test:
  - "cp travis_settings.py test_settings_local.py"

test_script:
  - "%PYTHON%/python.exe -m tox -e appveyor"
