environment:
  global:
    LXML_CACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\lxml-binaries"
  matrix:
    - PYTHON: "C:\\Python27-x64"

cache:
  - '%LXML_CACHE_DIR%'

services:
  - mongodb
  - mysql
  - postgresql

install:
  - "%PYTHON%/python.exe -m pip install tox"
  - ps: >-
      If(!(Test-Path $env:LXML_CACHE_DIR)) {
        Write-Host "Downloading lxml binaries";
        Start-Process -FilePath "git" -ArgumentList "clone https://gist.github.com/36d27f9b57f6e33bae0d.git $env:LXML_CACHE_DIR" -Wait;
      } Else {
        Write-Host "Updating lxml binaries";
        Start-Process -FilePath "git" -ArgumentList "pull" -WorkingDirectory "$env:LXML_CACHE_DIR" -Wait;
      }
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start

build: off

before_test:
  - "cp appveyor_settings.py test_settings_local.py"
  - ps: >-
      $env:MYSQL_PWD="Password12!"
      $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database grab_test;" --user=root'
      iex "& $cmd"
  - cmd: >-
      SET PGUSER=postgres
      SET PGPASSWORD=Password12!
      PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
      createdb YourDatabase

test_script:
  - "%PYTHON%/python.exe -m tox -e py-appveyor"
