environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
  - "%PYTHON%/python.exe -m pip install tox"
  - "%PYTHON%/python.exe -m pip install https://gist.github.com/jdemaeyer/36d27f9b57f6e33bae0d/raw/b1b3cd5f557226ea614de261c01a4e91102a8e67/lxml-3.5.0-cp27-none-win_amd64.whl"

build: off

before_test:
  - "cp travis_settings.py test_settings_local.py"

test_script:
  - "%PYTHON%/python.exe -m tox -e py-appveyor"
