environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
  - "%PYTHON%/python.exe -m pip install tox"
  - "%PYTHON%/python.exe -m pip install http://www.lfd.uci.edu/~gohlke/pythonlibs/f9r7rmd8/lxml-3.6.4-cp27-cp27m-win_amd64.whl"

build: off

before_test:
  - "cp travis_settings.py test_settings_local.py"

test_script:
  - "%PYTHON%/python.exe -m tox -e py-appveyor"
