environment:
  global:
    LXML_CACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\lxml-binaries"
  matrix:
    - PYTHON: "C:\\Python27-x64"

cache:
  - '%LXML_CACHE_DIR%'

services:
  - mongodb
  - mysql
  - postgresql

install:
  - "%PYTHON%/python.exe -m pip install tox"
  - ps: >-
      If(!(Test-Path $env:LXML_CACHE_DIR)) {
        Write-Host "Downloading lxml binaries";
        Start-Process -FilePath "git" -ArgumentList "clone https://gist.github.com/36d27f9b57f6e33bae0d.git $env:LXML_CACHE_DIR" -Wait;
      } Else {
        Write-Host "Updating lxml binaries";
        Start-Process -FilePath "git" -ArgumentList "pull" -WorkingDirectory "$env:LXML_CACHE_DIR" -Wait;
      }

# before_build and build steps install and run redis
before_build:
- choco install redis-64
- redis-server --service-install
- redis-server --service-start
- nuget restore .\Hangfire.Redis.StackExchange.sln

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

before_test:
  - "cp appveyor_settings.py test_settings_local.py"

test_script:
  - "%PYTHON%/python.exe -m tox -e py-appveyor"
